[package]
name = "slint_animations"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.18"
i-slint-backend-testing = { version = "1.18", default-features = false, features = ["ffi"] }
i-slint-core = { version = "1.18", default-features = false }

[build-dependencies]
slint-build = "1.18"
