// ============================================================
// 09_lists.io —— 第 09 章：列表
// 运行：io examples/09_lists/09_lists.io
//
// List 是 Io 里唯一的可变序列：list(...) 与 List clone 造出来的是同一种 List，
// 后者只是显式克隆原型。改造型方法（append / prepend / push / atPut /
// swapIndices / atInsert）返回**自身**，删除型方法（removeAt / pop /
// removeFirst）返回**被删掉的元素**——链式调用安不安全全看这一点。
// slice 在 List 上是原语、不警告，在 Sequence 上是 Io 方法、会打一行
// deprecation 警告；两者的区间语义其实一样（左闭右开）。
// ============================================================

fails := 0
chk := method(tag, got, want,
    if(got asString != want asString,
        fails = fails + 1
        writeln("  [FAIL] ", tag, " 得到 ", got asString, "，期望 ", want asString)
    )
)
sec := method(title, writeln(""); writeln("-- ", title))
show := method(label, value, writeln(label, " = ", value asString))

writeln("==== 09 开始 ====")

sec("9.1 list(...) 与 List clone：造出来的是同一种可变 List")
a := list(3, 1, 2)
b := List clone
show("list(3, 1, 2) 的 type", a type)
show("List clone 的 type", b type)
show("List clone 的 size", b size)
show("list() 的 size", list size)
show("两者的 proto 都是", a proto type)
b appendSeq(a)
show("b appendSeq(a) 之后 b", b asString)
show("b 是 a 本身吗", b isIdenticalTo(a))
a append(9)
show("再给 a append(9) 之后 a", a asString)
show("b 有没有跟着变", b asString)
chk("list 与 List clone 同型", a type asString, b type asString)
chk("clone 出来的新表是独立的", b asString, "list(3, 1, 2)")
chk("追加只改自己那一张", a asString, "list(3, 1, 2, 9)")

sec("9.2 就地修改：改造型返回自身，删除型返回被删掉的元素")
x := list(1, 2)
show("x append(3) 返回的就是 x 本身吗", (x append(3)) isIdenticalTo(x))
show("x prepend(0) 返回的就是 x 本身吗", (x prepend(0)) isIdenticalTo(x))
show("x atPut(0, 9) 返回的就是 x 本身吗", (x atPut(0, 9)) isIdenticalTo(x))
show("x push(7) 返回的就是 x 本身吗", (x push(7)) isIdenticalTo(x))
show("现在 x", x asString)
show("x removeAt(0) 返回的是被删掉的元素", x removeAt(0))
show("x pop 返回的是被删掉的元素", x pop)
show("删完之后的 x", x asString)
show("链式 append 是安全的", list(1) append(2) append(3))
e := try((list(1, 2) removeAt(0)) prepend(9))
show("拿 removeAt 的结果接着调 prepend 的异常消息", e error)
chk("append 返回自身", (x append(8)) isIdenticalTo(x), true)
chk("removeAt 返回元素而不是整张表", (list(5, 6) removeAt(0)) asString, "5")
chk("删除型的返回值不能接着链式调用", e error, "Number does not respond to 'prepend'")

sec("9.3 下标：at 支持负索引，越界返回 nil 而不是报错")
a = list(10, 20, 30)
show("a size", a size)
show("a at(0)", a at(0))
show("a at(-1)（最后一个）", a at(-1))
show("a at(-3)（第一个）", a at(-3))
show("a at(99) 是 nil 吗", (a at(99)) isNil)
show("a at(-99) 是 nil 吗", (a at(-99)) isNil)
show("first / last / second", list(a first, a last, a second) join(" / "))
ePut := try(a atPut(99, 1))
show("atPut 越界的内容是那句 index out of bounds 吗", (ePut error) containsSeq("index out of bounds"))
show("它尾巴上还带一个换行，size 是", (ePut error) size)
eIns := try(a atInsert(99, 1))
show("atInsert 越界也一样吗", (eIns error) containsSeq("index out of bounds"))
show("atInsert 异常消息的 size 也是", (eIns error) size)
chk("at 越界给 nil 而不是抛异常", a at(99) asString, "nil")
chk("负索引从尾部数", a at(-1), 30)
chk("atPut 越界报 index out of bounds", ePut error containsSeq("index out of bounds"), true)
chk("atInsert 的消息同样是 19 字符 + 一个换行", eIns error size, 20)

sec("9.4 slice 与 exSlice：区间语义一样，差别只有那条废弃警告")
a = list(1, 2, 3, 4, 5)
show("a slice(1, 3)", a slice(1, 3))
show("a exSlice(1, 3)", a exSlice(1, 3))
show("a exSlice(0, 0)（右端等于左端就是空表）", a exSlice(0, 0))
show("a slice(-2, -1)", a slice(-2, -1))
show("a exSlice(3, 99)（右端越界会截断）", a exSlice(3, 99))
show("List getSlot(\"slice\") 的 type", (List getSlot("slice")) type)
show("Sequence getSlot(\"slice\") 的 type", (Sequence getSlot("slice")) type)
show("在 doString 里对字符串调 slice，返回值是", Lobby doString("\"hello\" slice(1, 3)"))
chk("List 上 slice 与 exSlice 结果相同", a slice(1, 3) asString, a exSlice(1, 3) asString)
chk("exSlice 是左闭右开", a exSlice(1, 3), list(2, 3))
chk("空区间给空表", a exSlice(0, 0) asString, "list()")
chk("List 的 slice 是原语，不警告", (List getSlot("slice")) type, "CFunction")
chk("Sequence 的 slice 是 Io 方法，会警告", (Sequence getSlot("slice")) type, "Block")

sec("9.5 查找：indexOf / contains / detect，找不到给 nil 或 false")
a = list(10, 20, 30)
show("a indexOf(20)", a indexOf(20))
show("a indexOf(99) 是 nil 吗", (a indexOf(99)) isNil)
show("a contains(30)", a contains(30))
show("a contains(99)", a contains(99))
show("a detect(v, v > 15)", a detect(v, v > 15))
show("a detect(v, v > 999) 是 nil 吗", (a detect(v, v > 999)) isNil)
show("a detect(i, v, i == 2)", a detect(i, v, i == 2))
chk("indexOf 找不到是 nil", a indexOf(99) asString, "nil")
chk("contains 给布尔值", a contains(99), false)
chk("detect 找不到是 nil", a detect(v, v > 999) asString, "nil")

sec("9.6 排序：sort 返回新表，sortInPlace 就地，sortBy 收的是「比较器」")
a = list(3, 1, 2)
b = a sort
show("a sort 的返回值", b asString)
show("原表 a 有没有被改", a asString)
show("返回值是同一张表吗", b isIdenticalTo(a))
r := a sortInPlace
show("a sortInPlace 之后 a", a asString)
show("sortInPlace 返回的是 a 本身吗", r isIdenticalTo(a))
show("字符串按码点序排", list("b", "a", "C") sort)
show("数字按大小排（不是字符串序）", list(2, 10, 1) sort)
show("sortBy(block(x, y, x < y)) 升序", a sortBy(block(x, y, x < y)))
show("sortBy(block(x, y, x > y)) 降序", a sortBy(block(x, y, x > y)))
show("sortBy 之后原表还是", a asString)
u := list(5, 3, 9)
show("两个形参才是比较器：降序", u sortBy(block(x, y, x > y)))
show("只写一个形参、把 0 - v 当「键」", u sortBy(block(v, 0 - v)))
show("键换成常量字符串，结果一模一样", u sortBy(block(v, "zzz")))
pairs := list(list("b", 2), list("a", 1))
show("按第 0 位排序", (pairs sortBy(block(p, q, (p at(0)) < (q at(0)))) map(p, p at(0))) join(","))
show("sortByKey(at(0)) 之后取每个键", (pairs sortByKey(at(0)) map(p, p at(0))) join(","))
e = try(a sortBy(v, 0 - v))
show("sortBy(v, 0 - v) 的异常消息", e error)
chk("sort 不改原表", a asString, "list(1, 2, 3)")
chk("sort 返回的是新表", b isIdenticalTo(a), false)
chk("sortInPlace 返回自身", r isIdenticalTo(a), true)
chk("两参比较器才有效：降序", u sortBy(block(x, y, x > y)) asString, "list(9, 5, 3)")
chk("单参 block 的结果既不是升序", u sortBy(block(v, 0 - v)) asString != "list(3, 5, 9)", true)
chk("也不是降序——就是个错的结果", u sortBy(block(v, 0 - v)) asString != "list(9, 5, 3)", true)
chk("换个键结果不变，说明它压根没看键", u sortBy(block(v, "zzz")) asString, u sortBy(block(v, 0 - v)) asString)
chk("sortBy 的第一个实参必须是 block", e error, "Object does not respond to 'v'")

sec("9.7 变换：map / select / reduce / unique / reverse / flatten / join")
a = list(1, 2, 3, 4)
show("a map(v, v * 2)", a map(v, v * 2))
show("a map(i, v, i * 100 + v)", a map(i, v, i * 100 + v))
show("a select(v, v % 2 == 0)", a select(v, v % 2 == 0))
show("a select(i, v, i > 0)", a select(i, v, i > 0))
e = try(a reject(v, v % 2 == 0))
show("a reject(...) 的异常消息", e error)
show("用 select + not 顶替 reject", a select(v, (v % 2 == 0) not))
show("a reduce(+)", a reduce(+))
show("a reduce(x, y, x + y)", a reduce(x, y, x + y))
show("a reduce(x, y, x + y, 100)（末位是初值）", a reduce(x, y, x + y, 100))
show("a reverse join(\"-\")", a reverse join("-"))
show("a sum / a average", list(a sum, a average) join(" / "))
show("list(1, 2, 2, 3, 1) unique", list(1, 2, 2, 3, 1) unique)
n := list(1, list(2, list(3, 4)), 5)
show("嵌套表 flatten 之后 join", n flatten join("-"))
show("list(1, 2, 3) join(\"-\")", list(1, 2, 3) join("-"))
show("list() join(\"-\") 打出来是", "[" .. (list() join("-")) .. "]")
chk("map 返回新表", a map(v, v) isIdenticalTo(a), false)
chk("这一版的 List 根本没有 reject", e error, "List does not respond to 'reject'")
chk("reduce 三参形式", a reduce(x, y, x + y), 10)
chk("reduce 四参形式末位是初值", a reduce(x, y, x + y, 100), 110)
chk("flatten 会递归压平", n flatten join("-"), "1-2-3-4-5")
chk("空表 join 给空串", list() join("-"), "")

sec("9.8 嵌套表的打印陷阱，以及把方法装进列表")
nested := list(list(1, "a"), list(2, "b"))
show("nested at(0) 单独打印", nested at(0))
show("nested 整体打印", nested)
show("整体打印里出现了转义引号吗", nested asString containsSeq("\\\""))
show("所以嵌套表要自己拼", nested map(p, "[" .. (p at(0) asString) .. "," .. (p at(1)) .. "]") join(" "))
double := method(n, n * 2)
inc := method(n, n + 1)
fns := list(getSlot("double"), getSlot("inc"))
show("fns size", fns size)
show("取出来立刻 call 才行", list(fns at(0) call(10), fns at(1) call(10)) join(","))
e = try(fns map(f, f type))
show("想把方法先读进局部槽再用的异常消息", e error)
chk("同一个内层表单独打印是正常形态", nested at(0) asString, "list(1, \"a\")")
chk("整体打印却给内层元素加了引号", nested asString containsSeq("list(\"1\""), true)
chk("方法取出来立刻 call 是 20,11", list(fns at(0) call(10), fns at(1) call(10)) join(","), "20,11")
chk("读进来再用的局部槽会以零参激活方法", e error, "nil does not respond to '*'")

sec("9.9 自检")
chk("自检计数必须归零", fails, 0)
writeln("自检：", if(fails == 0, "全部通过", fails asString .. " 项失败"))

writeln("==== 09 结束 ====")
if(fails != 0, System exit(1))
