cabal-version:      2.4
name:               minilang
version:            0.1.0.0
build-type:         Simple

library
    exposed-modules:  Ast, Eval, Parser, Repl
    hs-source-dirs:   src
    build-depends:    base, containers, mtl, parsec
    default-language: Haskell2010

executable minilang
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:    base, minilang
    default-language: Haskell2010

test-suite minilang-test
    type:             exitcode-stdio-1.0
    main-is:          Spec.hs
    hs-source-dirs:   test
    build-depends:    base, containers, minilang
    default-language: Haskell2010
